apiVersion: v1
kind: Namespace
metadata:
  name: azdevops
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: azdevops
  namespace: azdevops
data:
  AZP_TOKEN: "qlwzt2ail6c7d6mon3ncefqwo3qxiknhyiijqdfhjva5vr4v6uga"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azdevops
  namespace: azdevops
  labels:
    app: azdevops-agent
data:
  AZP_POOL: "k8s-agents"
  AZP_URL: https://dev.azure.com/KRUSHNABHANAGE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: azdevops
  labels:
    app: azdevops-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: "k8s-agent"
        image: krushnabhanage10/azdo-slave:latest
        envFrom:
          - configMapRef:
              name: azdevops
          - secretRef:
              name: azdevops
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          requests:
            memory: 512Mi
            cpu: "150m"
        volumeMounts:
        - mountPath: /var/run/
          name: docker-volume
      - name: "docker"
        image: "docker:19.03.1-dind"
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/run/
          name: docker-volume
      volumes:
      - name: docker-volume
        emptyDir: {}
