apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: v1
kind: Namespace
metadata:
  name: azdevops
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: azdevopspat
  namespace: azdevops
data:
  AZP_TOKEN: "d2w3eG5pdGh5d2w1bm4yY241Y2c1a3BvcW50dnd6cm8zc3VzejJjZTZ4c3VzN2VkaTM2YQ=="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azdevopscm
  namespace: azdevops
  labels:
    app: azdevops-agent
data:
  AZP_POOL: "k8s-agents"
  AZP_URL: "https://dev.azure.com/KRUSHNABHANAGE"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: azdevops
  labels:
    app: azdevops-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: "k8s-agent"
        image: krushnabhanage10/azdo-slave:latest
        # env:
        # - name: AZP_TOKEN
        #   value: "wl7xnithywl5nn2cn5cg5kpoqntvwzro3susz2ce6xsus7edi36a"
        envFrom:
          - configMapRef:
              name: azdevopscm
          - secretRef:
              name: azdevopspat
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          requests:
            memory: 256Mi
            cpu: "150m"
        volumeMounts:
        - mountPath: /var/run/
          name: docker-volume
      - name: "docker"
        image: "docker:19.03.1-dind"
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/run/
          name: docker-volume
      volumes:
      - name: docker-volume
        emptyDir: {}